# Generated by Django 4.2.9 on 2024-01-25 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(default='', max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'филиал',
                'verbose_name_plural': 'филиалы',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('gender', models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=1, verbose_name='Пол')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=10)], verbose_name='Возраст')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
    ]
