# Generated by Django 4.2.9 on 2024-01-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
