# Generated by Django 4.2.9 on 2024-01-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_client_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='joined',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата регистрации'),
        ),
    ]
